// Code generated by protoc-gen-go. DO NOT EDIT.
// source: testgrid/config/config.proto

package config

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TestGroup_TestsName int32

const (
	TestGroup_TESTS_NAME_MIN     TestGroup_TestsName = 0
	TestGroup_TESTS_NAME_IGNORE  TestGroup_TestsName = 1
	TestGroup_TESTS_NAME_REPLACE TestGroup_TestsName = 2
	TestGroup_TESTS_NAME_APPEND  TestGroup_TestsName = 3
)

var TestGroup_TestsName_name = map[int32]string{
	0: "TESTS_NAME_MIN",
	1: "TESTS_NAME_IGNORE",
	2: "TESTS_NAME_REPLACE",
	3: "TESTS_NAME_APPEND",
}
var TestGroup_TestsName_value = map[string]int32{
	"TESTS_NAME_MIN":     0,
	"TESTS_NAME_IGNORE":  1,
	"TESTS_NAME_REPLACE": 2,
	"TESTS_NAME_APPEND":  3,
}

func (x TestGroup_TestsName) String() string {
	return proto.EnumName(TestGroup_TestsName_name, int32(x))
}
func (TestGroup_TestsName) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_config_b08ec77469bf26cf, []int{2, 0}
}

type TestNameConfig struct {
	NameElements         []*TestNameConfig_NameElement `protobuf:"bytes,1,rep,name=name_elements,json=nameElements,proto3" json:"name_elements,omitempty"`
	NameFormat           string                        `protobuf:"bytes,2,opt,name=name_format,json=nameFormat,proto3" json:"name_format,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *TestNameConfig) Reset()         { *m = TestNameConfig{} }
func (m *TestNameConfig) String() string { return proto.CompactTextString(m) }
func (*TestNameConfig) ProtoMessage()    {}
func (*TestNameConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_config_b08ec77469bf26cf, []int{0}
}
func (m *TestNameConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestNameConfig.Unmarshal(m, b)
}
func (m *TestNameConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestNameConfig.Marshal(b, m, deterministic)
}
func (dst *TestNameConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestNameConfig.Merge(dst, src)
}
func (m *TestNameConfig) XXX_Size() int {
	return xxx_messageInfo_TestNameConfig.Size(m)
}
func (m *TestNameConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_TestNameConfig.DiscardUnknown(m)
}

var xxx_messageInfo_TestNameConfig proto.InternalMessageInfo

func (m *TestNameConfig) GetNameElements() []*TestNameConfig_NameElement {
	if m != nil {
		return m.NameElements
	}
	return nil
}

func (m *TestNameConfig) GetNameFormat() string {
	if m != nil {
		return m.NameFormat
	}
	return ""
}

type TestNameConfig_NameElement struct {
	TargetConfig         string   `protobuf:"bytes,2,opt,name=target_config,json=targetConfig,proto3" json:"target_config,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestNameConfig_NameElement) Reset()         { *m = TestNameConfig_NameElement{} }
func (m *TestNameConfig_NameElement) String() string { return proto.CompactTextString(m) }
func (*TestNameConfig_NameElement) ProtoMessage()    {}
func (*TestNameConfig_NameElement) Descriptor() ([]byte, []int) {
	return fileDescriptor_config_b08ec77469bf26cf, []int{0, 0}
}
func (m *TestNameConfig_NameElement) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestNameConfig_NameElement.Unmarshal(m, b)
}
func (m *TestNameConfig_NameElement) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestNameConfig_NameElement.Marshal(b, m, deterministic)
}
func (dst *TestNameConfig_NameElement) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestNameConfig_NameElement.Merge(dst, src)
}
func (m *TestNameConfig_NameElement) XXX_Size() int {
	return xxx_messageInfo_TestNameConfig_NameElement.Size(m)
}
func (m *TestNameConfig_NameElement) XXX_DiscardUnknown() {
	xxx_messageInfo_TestNameConfig_NameElement.DiscardUnknown(m)
}

var xxx_messageInfo_TestNameConfig_NameElement proto.InternalMessageInfo

func (m *TestNameConfig_NameElement) GetTargetConfig() string {
	if m != nil {
		return m.TargetConfig
	}
	return ""
}

type Notification struct {
	Summary              string   `protobuf:"bytes,1,opt,name=summary,proto3" json:"summary,omitempty"`
	ContextLink          string   `protobuf:"bytes,2,opt,name=context_link,json=contextLink,proto3" json:"context_link,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Notification) Reset()         { *m = Notification{} }
func (m *Notification) String() string { return proto.CompactTextString(m) }
func (*Notification) ProtoMessage()    {}
func (*Notification) Descriptor() ([]byte, []int) {
	return fileDescriptor_config_b08ec77469bf26cf, []int{1}
}
func (m *Notification) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Notification.Unmarshal(m, b)
}
func (m *Notification) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Notification.Marshal(b, m, deterministic)
}
func (dst *Notification) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Notification.Merge(dst, src)
}
func (m *Notification) XXX_Size() int {
	return xxx_messageInfo_Notification.Size(m)
}
func (m *Notification) XXX_DiscardUnknown() {
	xxx_messageInfo_Notification.DiscardUnknown(m)
}

var xxx_messageInfo_Notification proto.InternalMessageInfo

func (m *Notification) GetSummary() string {
	if m != nil {
		return m.Summary
	}
	return ""
}

func (m *Notification) GetContextLink() string {
	if m != nil {
		return m.ContextLink
	}
	return ""
}

type TestGroup struct {
	Name                    string                    `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	GcsPrefix               string                    `protobuf:"bytes,2,opt,name=gcs_prefix,json=gcsPrefix,proto3" json:"gcs_prefix,omitempty"`
	DaysOfResults           int32                     `protobuf:"varint,3,opt,name=days_of_results,json=daysOfResults,proto3" json:"days_of_results,omitempty"`
	IgnorePending           bool                      `protobuf:"varint,4,opt,name=ignore_pending,json=ignorePending,proto3" json:"ignore_pending,omitempty"`
	TestsNamePolicy         TestGroup_TestsName       `protobuf:"varint,6,opt,name=tests_name_policy,json=testsNamePolicy,proto3,enum=TestGroup_TestsName" json:"tests_name_policy,omitempty"`
	ColumnHeader            []*TestGroup_ColumnHeader `protobuf:"bytes,9,rep,name=column_header,json=columnHeader,proto3" json:"column_header,omitempty"`
	AlertStaleResultsHours  int32                     `protobuf:"varint,11,opt,name=alert_stale_results_hours,json=alertStaleResultsHours,proto3" json:"alert_stale_results_hours,omitempty"`
	NumFailuresToAlert      int32                     `protobuf:"varint,12,opt,name=num_failures_to_alert,json=numFailuresToAlert,proto3" json:"num_failures_to_alert,omitempty"`
	CodeSearchPath          string                    `protobuf:"bytes,14,opt,name=code_search_path,json=codeSearchPath,proto3" json:"code_search_path,omitempty"`
	NumColumnsRecent        int32                     `protobuf:"varint,15,opt,name=num_columns_recent,json=numColumnsRecent,proto3" json:"num_columns_recent,omitempty"`
	UseKubernetesClient     bool                      `protobuf:"varint,24,opt,name=use_kubernetes_client,json=useKubernetesClient,proto3" json:"use_kubernetes_client,omitempty"`
	IsExternal              bool                      `protobuf:"varint,25,opt,name=is_external,json=isExternal,proto3" json:"is_external,omitempty"`
	TestNameConfig          *TestNameConfig           `protobuf:"bytes,26,opt,name=test_name_config,json=testNameConfig,proto3" json:"test_name_config,omitempty"`
	Notifications           []*Notification           `protobuf:"bytes,27,rep,name=notifications,proto3" json:"notifications,omitempty"`
	NumPassesToDisableAlert int32                     `protobuf:"varint,38,opt,name=num_passes_to_disable_alert,json=numPassesToDisableAlert,proto3" json:"num_passes_to_disable_alert,omitempty"`
	ShortTextMetric         string                    `protobuf:"bytes,43,opt,name=short_text_metric,json=shortTextMetric,proto3" json:"short_text_metric,omitempty"`
	XXX_NoUnkeyedLiteral    struct{}                  `json:"-"`
	XXX_unrecognized        []byte                    `json:"-"`
	XXX_sizecache           int32                     `json:"-"`
}

func (m *TestGroup) Reset()         { *m = TestGroup{} }
func (m *TestGroup) String() string { return proto.CompactTextString(m) }
func (*TestGroup) ProtoMessage()    {}
func (*TestGroup) Descriptor() ([]byte, []int) {
	return fileDescriptor_config_b08ec77469bf26cf, []int{2}
}
func (m *TestGroup) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestGroup.Unmarshal(m, b)
}
func (m *TestGroup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestGroup.Marshal(b, m, deterministic)
}
func (dst *TestGroup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestGroup.Merge(dst, src)
}
func (m *TestGroup) XXX_Size() int {
	return xxx_messageInfo_TestGroup.Size(m)
}
func (m *TestGroup) XXX_DiscardUnknown() {
	xxx_messageInfo_TestGroup.DiscardUnknown(m)
}

var xxx_messageInfo_TestGroup proto.InternalMessageInfo

func (m *TestGroup) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TestGroup) GetGcsPrefix() string {
	if m != nil {
		return m.GcsPrefix
	}
	return ""
}

func (m *TestGroup) GetDaysOfResults() int32 {
	if m != nil {
		return m.DaysOfResults
	}
	return 0
}

func (m *TestGroup) GetIgnorePending() bool {
	if m != nil {
		return m.IgnorePending
	}
	return false
}

func (m *TestGroup) GetTestsNamePolicy() TestGroup_TestsName {
	if m != nil {
		return m.TestsNamePolicy
	}
	return TestGroup_TESTS_NAME_MIN
}

func (m *TestGroup) GetColumnHeader() []*TestGroup_ColumnHeader {
	if m != nil {
		return m.ColumnHeader
	}
	return nil
}

func (m *TestGroup) GetAlertStaleResultsHours() int32 {
	if m != nil {
		return m.AlertStaleResultsHours
	}
	return 0
}

func (m *TestGroup) GetNumFailuresToAlert() int32 {
	if m != nil {
		return m.NumFailuresToAlert
	}
	return 0
}

func (m *TestGroup) GetCodeSearchPath() string {
	if m != nil {
		return m.CodeSearchPath
	}
	return ""
}

func (m *TestGroup) GetNumColumnsRecent() int32 {
	if m != nil {
		return m.NumColumnsRecent
	}
	return 0
}

func (m *TestGroup) GetUseKubernetesClient() bool {
	if m != nil {
		return m.UseKubernetesClient
	}
	return false
}

func (m *TestGroup) GetIsExternal() bool {
	if m != nil {
		return m.IsExternal
	}
	return false
}

func (m *TestGroup) GetTestNameConfig() *TestNameConfig {
	if m != nil {
		return m.TestNameConfig
	}
	return nil
}

func (m *TestGroup) GetNotifications() []*Notification {
	if m != nil {
		return m.Notifications
	}
	return nil
}

func (m *TestGroup) GetNumPassesToDisableAlert() int32 {
	if m != nil {
		return m.NumPassesToDisableAlert
	}
	return 0
}

func (m *TestGroup) GetShortTextMetric() string {
	if m != nil {
		return m.ShortTextMetric
	}
	return ""
}

type TestGroup_ColumnHeader struct {
	ConfigurationValue   string   `protobuf:"bytes,3,opt,name=configuration_value,json=configurationValue,proto3" json:"configuration_value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestGroup_ColumnHeader) Reset()         { *m = TestGroup_ColumnHeader{} }
func (m *TestGroup_ColumnHeader) String() string { return proto.CompactTextString(m) }
func (*TestGroup_ColumnHeader) ProtoMessage()    {}
func (*TestGroup_ColumnHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_config_b08ec77469bf26cf, []int{2, 0}
}
func (m *TestGroup_ColumnHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestGroup_ColumnHeader.Unmarshal(m, b)
}
func (m *TestGroup_ColumnHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestGroup_ColumnHeader.Marshal(b, m, deterministic)
}
func (dst *TestGroup_ColumnHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestGroup_ColumnHeader.Merge(dst, src)
}
func (m *TestGroup_ColumnHeader) XXX_Size() int {
	return xxx_messageInfo_TestGroup_ColumnHeader.Size(m)
}
func (m *TestGroup_ColumnHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_TestGroup_ColumnHeader.DiscardUnknown(m)
}

var xxx_messageInfo_TestGroup_ColumnHeader proto.InternalMessageInfo

func (m *TestGroup_ColumnHeader) GetConfigurationValue() string {
	if m != nil {
		return m.ConfigurationValue
	}
	return ""
}

type Dashboard struct {
	DashboardTab         []*DashboardTab `protobuf:"bytes,1,rep,name=dashboard_tab,json=dashboardTab,proto3" json:"dashboard_tab,omitempty"`
	Name                 string          `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Notifications        []*Notification `protobuf:"bytes,3,rep,name=notifications,proto3" json:"notifications,omitempty"`
	DefaultTab           string          `protobuf:"bytes,5,opt,name=default_tab,json=defaultTab,proto3" json:"default_tab,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Dashboard) Reset()         { *m = Dashboard{} }
func (m *Dashboard) String() string { return proto.CompactTextString(m) }
func (*Dashboard) ProtoMessage()    {}
func (*Dashboard) Descriptor() ([]byte, []int) {
	return fileDescriptor_config_b08ec77469bf26cf, []int{3}
}
func (m *Dashboard) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Dashboard.Unmarshal(m, b)
}
func (m *Dashboard) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Dashboard.Marshal(b, m, deterministic)
}
func (dst *Dashboard) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Dashboard.Merge(dst, src)
}
func (m *Dashboard) XXX_Size() int {
	return xxx_messageInfo_Dashboard.Size(m)
}
func (m *Dashboard) XXX_DiscardUnknown() {
	xxx_messageInfo_Dashboard.DiscardUnknown(m)
}

var xxx_messageInfo_Dashboard proto.InternalMessageInfo

func (m *Dashboard) GetDashboardTab() []*DashboardTab {
	if m != nil {
		return m.DashboardTab
	}
	return nil
}

func (m *Dashboard) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Dashboard) GetNotifications() []*Notification {
	if m != nil {
		return m.Notifications
	}
	return nil
}

func (m *Dashboard) GetDefaultTab() string {
	if m != nil {
		return m.DefaultTab
	}
	return ""
}

type LinkTemplate struct {
	Url                  string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Options              []*LinkOptionsTemplate `protobuf:"bytes,2,rep,name=options,proto3" json:"options,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *LinkTemplate) Reset()         { *m = LinkTemplate{} }
func (m *LinkTemplate) String() string { return proto.CompactTextString(m) }
func (*LinkTemplate) ProtoMessage()    {}
func (*LinkTemplate) Descriptor() ([]byte, []int) {
	return fileDescriptor_config_b08ec77469bf26cf, []int{4}
}
func (m *LinkTemplate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LinkTemplate.Unmarshal(m, b)
}
func (m *LinkTemplate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LinkTemplate.Marshal(b, m, deterministic)
}
func (dst *LinkTemplate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LinkTemplate.Merge(dst, src)
}
func (m *LinkTemplate) XXX_Size() int {
	return xxx_messageInfo_LinkTemplate.Size(m)
}
func (m *LinkTemplate) XXX_DiscardUnknown() {
	xxx_messageInfo_LinkTemplate.DiscardUnknown(m)
}

var xxx_messageInfo_LinkTemplate proto.InternalMessageInfo

func (m *LinkTemplate) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *LinkTemplate) GetOptions() []*LinkOptionsTemplate {
	if m != nil {
		return m.Options
	}
	return nil
}

type LinkOptionsTemplate struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LinkOptionsTemplate) Reset()         { *m = LinkOptionsTemplate{} }
func (m *LinkOptionsTemplate) String() string { return proto.CompactTextString(m) }
func (*LinkOptionsTemplate) ProtoMessage()    {}
func (*LinkOptionsTemplate) Descriptor() ([]byte, []int) {
	return fileDescriptor_config_b08ec77469bf26cf, []int{5}
}
func (m *LinkOptionsTemplate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LinkOptionsTemplate.Unmarshal(m, b)
}
func (m *LinkOptionsTemplate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LinkOptionsTemplate.Marshal(b, m, deterministic)
}
func (dst *LinkOptionsTemplate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LinkOptionsTemplate.Merge(dst, src)
}
func (m *LinkOptionsTemplate) XXX_Size() int {
	return xxx_messageInfo_LinkOptionsTemplate.Size(m)
}
func (m *LinkOptionsTemplate) XXX_DiscardUnknown() {
	xxx_messageInfo_LinkOptionsTemplate.DiscardUnknown(m)
}

var xxx_messageInfo_LinkOptionsTemplate proto.InternalMessageInfo

func (m *LinkOptionsTemplate) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *LinkOptionsTemplate) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type DashboardTab struct {
	Name                  string                    `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	TestGroupName         string                    `protobuf:"bytes,2,opt,name=test_group_name,json=testGroupName,proto3" json:"test_group_name,omitempty"`
	BugComponent          int32                     `protobuf:"varint,3,opt,name=bug_component,json=bugComponent,proto3" json:"bug_component,omitempty"`
	CodeSearchPath        string                    `protobuf:"bytes,4,opt,name=code_search_path,json=codeSearchPath,proto3" json:"code_search_path,omitempty"`
	NumColumnsRecent      int32                     `protobuf:"varint,5,opt,name=num_columns_recent,json=numColumnsRecent,proto3" json:"num_columns_recent,omitempty"`
	BaseOptions           string                    `protobuf:"bytes,6,opt,name=base_options,json=baseOptions,proto3" json:"base_options,omitempty"`
	OpenTestTemplate      *LinkTemplate             `protobuf:"bytes,7,opt,name=open_test_template,json=openTestTemplate,proto3" json:"open_test_template,omitempty"`
	FileBugTemplate       *LinkTemplate             `protobuf:"bytes,8,opt,name=file_bug_template,json=fileBugTemplate,proto3" json:"file_bug_template,omitempty"`
	AttachBugTemplate     *LinkTemplate             `protobuf:"bytes,9,opt,name=attach_bug_template,json=attachBugTemplate,proto3" json:"attach_bug_template,omitempty"`
	ResultsText           string                    `protobuf:"bytes,10,opt,name=results_text,json=resultsText,proto3" json:"results_text,omitempty"`
	ResultsUrlTemplate    *LinkTemplate             `protobuf:"bytes,11,opt,name=results_url_template,json=resultsUrlTemplate,proto3" json:"results_url_template,omitempty"`
	CodeSearchUrlTemplate *LinkTemplate             `protobuf:"bytes,12,opt,name=code_search_url_template,json=codeSearchUrlTemplate,proto3" json:"code_search_url_template,omitempty"`
	Description           string                    `protobuf:"bytes,13,opt,name=description,proto3" json:"description,omitempty"`
	AlertOptions          *DashboardTabAlertOptions `protobuf:"bytes,15,opt,name=alert_options,json=alertOptions,proto3" json:"alert_options,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}                  `json:"-"`
	XXX_unrecognized      []byte                    `json:"-"`
	XXX_sizecache         int32                     `json:"-"`
}

func (m *DashboardTab) Reset()         { *m = DashboardTab{} }
func (m *DashboardTab) String() string { return proto.CompactTextString(m) }
func (*DashboardTab) ProtoMessage()    {}
func (*DashboardTab) Descriptor() ([]byte, []int) {
	return fileDescriptor_config_b08ec77469bf26cf, []int{6}
}
func (m *DashboardTab) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DashboardTab.Unmarshal(m, b)
}
func (m *DashboardTab) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DashboardTab.Marshal(b, m, deterministic)
}
func (dst *DashboardTab) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DashboardTab.Merge(dst, src)
}
func (m *DashboardTab) XXX_Size() int {
	return xxx_messageInfo_DashboardTab.Size(m)
}
func (m *DashboardTab) XXX_DiscardUnknown() {
	xxx_messageInfo_DashboardTab.DiscardUnknown(m)
}

var xxx_messageInfo_DashboardTab proto.InternalMessageInfo

func (m *DashboardTab) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DashboardTab) GetTestGroupName() string {
	if m != nil {
		return m.TestGroupName
	}
	return ""
}

func (m *DashboardTab) GetBugComponent() int32 {
	if m != nil {
		return m.BugComponent
	}
	return 0
}

func (m *DashboardTab) GetCodeSearchPath() string {
	if m != nil {
		return m.CodeSearchPath
	}
	return ""
}

func (m *DashboardTab) GetNumColumnsRecent() int32 {
	if m != nil {
		return m.NumColumnsRecent
	}
	return 0
}

func (m *DashboardTab) GetBaseOptions() string {
	if m != nil {
		return m.BaseOptions
	}
	return ""
}

func (m *DashboardTab) GetOpenTestTemplate() *LinkTemplate {
	if m != nil {
		return m.OpenTestTemplate
	}
	return nil
}

func (m *DashboardTab) GetFileBugTemplate() *LinkTemplate {
	if m != nil {
		return m.FileBugTemplate
	}
	return nil
}

func (m *DashboardTab) GetAttachBugTemplate() *LinkTemplate {
	if m != nil {
		return m.AttachBugTemplate
	}
	return nil
}

func (m *DashboardTab) GetResultsText() string {
	if m != nil {
		return m.ResultsText
	}
	return ""
}

func (m *DashboardTab) GetResultsUrlTemplate() *LinkTemplate {
	if m != nil {
		return m.ResultsUrlTemplate
	}
	return nil
}

func (m *DashboardTab) GetCodeSearchUrlTemplate() *LinkTemplate {
	if m != nil {
		return m.CodeSearchUrlTemplate
	}
	return nil
}

func (m *DashboardTab) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *DashboardTab) GetAlertOptions() *DashboardTabAlertOptions {
	if m != nil {
		return m.AlertOptions
	}
	return nil
}

type DashboardTabAlertOptions struct {
	AlertStaleResultsHours int32    `protobuf:"varint,1,opt,name=alert_stale_results_hours,json=alertStaleResultsHours,proto3" json:"alert_stale_results_hours,omitempty"`
	NumFailuresToAlert     int32    `protobuf:"varint,2,opt,name=num_failures_to_alert,json=numFailuresToAlert,proto3" json:"num_failures_to_alert,omitempty"`
	AlertMailToAddresses   string   `protobuf:"bytes,3,opt,name=alert_mail_to_addresses,json=alertMailToAddresses,proto3" json:"alert_mail_to_addresses,omitempty"`
	XXX_NoUnkeyedLiteral   struct{} `json:"-"`
	XXX_unrecognized       []byte   `json:"-"`
	XXX_sizecache          int32    `json:"-"`
}

func (m *DashboardTabAlertOptions) Reset()         { *m = DashboardTabAlertOptions{} }
func (m *DashboardTabAlertOptions) String() string { return proto.CompactTextString(m) }
func (*DashboardTabAlertOptions) ProtoMessage()    {}
func (*DashboardTabAlertOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_config_b08ec77469bf26cf, []int{7}
}
func (m *DashboardTabAlertOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DashboardTabAlertOptions.Unmarshal(m, b)
}
func (m *DashboardTabAlertOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DashboardTabAlertOptions.Marshal(b, m, deterministic)
}
func (dst *DashboardTabAlertOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DashboardTabAlertOptions.Merge(dst, src)
}
func (m *DashboardTabAlertOptions) XXX_Size() int {
	return xxx_messageInfo_DashboardTabAlertOptions.Size(m)
}
func (m *DashboardTabAlertOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_DashboardTabAlertOptions.DiscardUnknown(m)
}

var xxx_messageInfo_DashboardTabAlertOptions proto.InternalMessageInfo

func (m *DashboardTabAlertOptions) GetAlertStaleResultsHours() int32 {
	if m != nil {
		return m.AlertStaleResultsHours
	}
	return 0
}

func (m *DashboardTabAlertOptions) GetNumFailuresToAlert() int32 {
	if m != nil {
		return m.NumFailuresToAlert
	}
	return 0
}

func (m *DashboardTabAlertOptions) GetAlertMailToAddresses() string {
	if m != nil {
		return m.AlertMailToAddresses
	}
	return ""
}

type DashboardGroup struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	DashboardNames       []string `protobuf:"bytes,2,rep,name=dashboard_names,json=dashboardNames,proto3" json:"dashboard_names,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DashboardGroup) Reset()         { *m = DashboardGroup{} }
func (m *DashboardGroup) String() string { return proto.CompactTextString(m) }
func (*DashboardGroup) ProtoMessage()    {}
func (*DashboardGroup) Descriptor() ([]byte, []int) {
	return fileDescriptor_config_b08ec77469bf26cf, []int{8}
}
func (m *DashboardGroup) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DashboardGroup.Unmarshal(m, b)
}
func (m *DashboardGroup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DashboardGroup.Marshal(b, m, deterministic)
}
func (dst *DashboardGroup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DashboardGroup.Merge(dst, src)
}
func (m *DashboardGroup) XXX_Size() int {
	return xxx_messageInfo_DashboardGroup.Size(m)
}
func (m *DashboardGroup) XXX_DiscardUnknown() {
	xxx_messageInfo_DashboardGroup.DiscardUnknown(m)
}

var xxx_messageInfo_DashboardGroup proto.InternalMessageInfo

func (m *DashboardGroup) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DashboardGroup) GetDashboardNames() []string {
	if m != nil {
		return m.DashboardNames
	}
	return nil
}

type Configuration struct {
	TestGroups           []*TestGroup      `protobuf:"bytes,1,rep,name=test_groups,json=testGroups,proto3" json:"test_groups,omitempty"`
	Dashboards           []*Dashboard      `protobuf:"bytes,2,rep,name=dashboards,proto3" json:"dashboards,omitempty"`
	DashboardGroups      []*DashboardGroup `protobuf:"bytes,3,rep,name=dashboard_groups,json=dashboardGroups,proto3" json:"dashboard_groups,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Configuration) Reset()         { *m = Configuration{} }
func (m *Configuration) String() string { return proto.CompactTextString(m) }
func (*Configuration) ProtoMessage()    {}
func (*Configuration) Descriptor() ([]byte, []int) {
	return fileDescriptor_config_b08ec77469bf26cf, []int{9}
}
func (m *Configuration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Configuration.Unmarshal(m, b)
}
func (m *Configuration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Configuration.Marshal(b, m, deterministic)
}
func (dst *Configuration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Configuration.Merge(dst, src)
}
func (m *Configuration) XXX_Size() int {
	return xxx_messageInfo_Configuration.Size(m)
}
func (m *Configuration) XXX_DiscardUnknown() {
	xxx_messageInfo_Configuration.DiscardUnknown(m)
}

var xxx_messageInfo_Configuration proto.InternalMessageInfo

func (m *Configuration) GetTestGroups() []*TestGroup {
	if m != nil {
		return m.TestGroups
	}
	return nil
}

func (m *Configuration) GetDashboards() []*Dashboard {
	if m != nil {
		return m.Dashboards
	}
	return nil
}

func (m *Configuration) GetDashboardGroups() []*DashboardGroup {
	if m != nil {
		return m.DashboardGroups
	}
	return nil
}

type DefaultConfiguration struct {
	DefaultTestGroup     *TestGroup    `protobuf:"bytes,1,opt,name=default_test_group,json=defaultTestGroup,proto3" json:"default_test_group,omitempty"`
	DefaultDashboardTab  *DashboardTab `protobuf:"bytes,2,opt,name=default_dashboard_tab,json=defaultDashboardTab,proto3" json:"default_dashboard_tab,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *DefaultConfiguration) Reset()         { *m = DefaultConfiguration{} }
func (m *DefaultConfiguration) String() string { return proto.CompactTextString(m) }
func (*DefaultConfiguration) ProtoMessage()    {}
func (*DefaultConfiguration) Descriptor() ([]byte, []int) {
	return fileDescriptor_config_b08ec77469bf26cf, []int{10}
}
func (m *DefaultConfiguration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DefaultConfiguration.Unmarshal(m, b)
}
func (m *DefaultConfiguration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DefaultConfiguration.Marshal(b, m, deterministic)
}
func (dst *DefaultConfiguration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DefaultConfiguration.Merge(dst, src)
}
func (m *DefaultConfiguration) XXX_Size() int {
	return xxx_messageInfo_DefaultConfiguration.Size(m)
}
func (m *DefaultConfiguration) XXX_DiscardUnknown() {
	xxx_messageInfo_DefaultConfiguration.DiscardUnknown(m)
}

var xxx_messageInfo_DefaultConfiguration proto.InternalMessageInfo

func (m *DefaultConfiguration) GetDefaultTestGroup() *TestGroup {
	if m != nil {
		return m.DefaultTestGroup
	}
	return nil
}

func (m *DefaultConfiguration) GetDefaultDashboardTab() *DashboardTab {
	if m != nil {
		return m.DefaultDashboardTab
	}
	return nil
}

func init() {
	proto.RegisterType((*TestNameConfig)(nil), "TestNameConfig")
	proto.RegisterType((*TestNameConfig_NameElement)(nil), "TestNameConfig.NameElement")
	proto.RegisterType((*Notification)(nil), "Notification")
	proto.RegisterType((*TestGroup)(nil), "TestGroup")
	proto.RegisterType((*TestGroup_ColumnHeader)(nil), "TestGroup.ColumnHeader")
	proto.RegisterType((*Dashboard)(nil), "Dashboard")
	proto.RegisterType((*LinkTemplate)(nil), "LinkTemplate")
	proto.RegisterType((*LinkOptionsTemplate)(nil), "LinkOptionsTemplate")
	proto.RegisterType((*DashboardTab)(nil), "DashboardTab")
	proto.RegisterType((*DashboardTabAlertOptions)(nil), "DashboardTabAlertOptions")
	proto.RegisterType((*DashboardGroup)(nil), "DashboardGroup")
	proto.RegisterType((*Configuration)(nil), "Configuration")
	proto.RegisterType((*DefaultConfiguration)(nil), "DefaultConfiguration")
	proto.RegisterEnum("TestGroup_TestsName", TestGroup_TestsName_name, TestGroup_TestsName_value)
}

func init() {
	proto.RegisterFile("testgrid/config/config.proto", fileDescriptor_config_b08ec77469bf26cf)
}

var fileDescriptor_config_b08ec77469bf26cf = []byte{
	// 1304 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x56, 0xdb, 0x6e, 0xdb, 0xb6,
	0x1b, 0xff, 0xcb, 0x91, 0x13, 0xf9, 0xb3, 0x64, 0x2b, 0x4c, 0xd2, 0xaa, 0x87, 0x3f, 0xea, 0xba,
	0x58, 0x66, 0xb4, 0x83, 0x8b, 0xa5, 0x18, 0xb0, 0x6e, 0xed, 0xd6, 0x2c, 0x71, 0x0f, 0x6e, 0x93,
	0x1a, 0x8a, 0xb7, 0x5b, 0x82, 0x96, 0x69, 0x5b, 0x88, 0x0e, 0x06, 0x49, 0x0d, 0xe9, 0x73, 0xec,
	0x15, 0x76, 0xbf, 0xab, 0x5d, 0xec, 0x6a, 0xaf, 0xb2, 0x47, 0x19, 0x48, 0x4a, 0xb2, 0xdc, 0x39,
	0xc3, 0xb6, 0x2b, 0x91, 0xbf, 0xef, 0x40, 0x7e, 0xa7, 0x9f, 0x08, 0x77, 0x05, 0xe5, 0x62, 0xce,
	0xc2, 0xe9, 0xe3, 0x20, 0x4d, 0x66, 0xe1, 0x3c, 0xff, 0xf4, 0x97, 0x2c, 0x15, 0x69, 0xf7, 0x37,
	0x03, 0x5a, 0x63, 0xca, 0xc5, 0x39, 0x89, 0xe9, 0x89, 0x12, 0xa0, 0x17, 0xe0, 0x24, 0x24, 0xa6,
	0x98, 0x46, 0x34, 0xa6, 0x89, 0xe0, 0x9e, 0xd1, 0xd9, 0xea, 0x35, 0x8f, 0xee, 0xf4, 0xd7, 0xf5,
	0xfa, 0x72, 0x39, 0xd0, 0x3a, 0xbe, 0x9d, 0xac, 0x36, 0x1c, 0xdd, 0x83, 0xa6, 0xf2, 0x30, 0x4b,
	0x59, 0x4c, 0x84, 0x57, 0xeb, 0x18, 0xbd, 0x86, 0x0f, 0x12, 0x7a, 0xa9, 0x90, 0xdb, 0xa7, 0xd0,
	0xac, 0x58, 0xa3, 0x07, 0xe0, 0x08, 0xc2, 0xe6, 0x54, 0x60, 0x7d, 0xb7, 0xdc, 0xc2, 0xd6, 0xa0,
	0x3e, 0x6e, 0x68, 0x5a, 0x86, 0x5b, 0x1b, 0x9a, 0xd6, 0x96, 0x6b, 0x0e, 0x4d, 0xcb, 0x74, 0xeb,
	0xdd, 0xb7, 0x60, 0x9f, 0xa7, 0x22, 0x9c, 0x85, 0x01, 0x11, 0x61, 0x9a, 0x20, 0x0f, 0x76, 0x78,
	0x16, 0xc7, 0x84, 0x7d, 0xf0, 0x0c, 0xe5, 0xa0, 0xd8, 0xa2, 0xfb, 0x60, 0x07, 0x69, 0x22, 0xe8,
	0x95, 0xc0, 0x51, 0x98, 0x5c, 0xe6, 0xfe, 0x9b, 0x39, 0xf6, 0x2e, 0x4c, 0x2e, 0xbb, 0x7f, 0xec,
	0x40, 0x43, 0x06, 0xf8, 0x8a, 0xa5, 0xd9, 0x12, 0x21, 0x30, 0xe5, 0x75, 0x73, 0x3f, 0x6a, 0x8d,
	0xfe, 0x0f, 0x30, 0x0f, 0x38, 0x5e, 0x32, 0x3a, 0x0b, 0xaf, 0x72, 0x17, 0x8d, 0x79, 0xc0, 0x47,
	0x0a, 0x40, 0x87, 0xd0, 0x9e, 0x92, 0x0f, 0x1c, 0xa7, 0x33, 0xcc, 0x28, 0xcf, 0x22, 0xc1, 0xbd,
	0xad, 0x8e, 0xd1, 0xab, 0xfb, 0x8e, 0x84, 0xdf, 0xcf, 0x7c, 0x0d, 0xa2, 0x4f, 0xa0, 0x15, 0xce,
	0x93, 0x94, 0x51, 0xbc, 0xa4, 0xc9, 0x34, 0x4c, 0xe6, 0x9e, 0xd9, 0x31, 0x7a, 0x96, 0xef, 0x68,
	0x74, 0xa4, 0x41, 0xf4, 0x02, 0x76, 0x65, 0xe1, 0x38, 0x56, 0x99, 0x5c, 0xa6, 0x51, 0x18, 0x7c,
	0xf0, 0xb6, 0x3b, 0x46, 0xaf, 0x75, 0xb4, 0xdf, 0x2f, 0x2f, 0xaa, 0x56, 0x5c, 0xe6, 0xd2, 0x6f,
	0x8b, 0x62, 0x39, 0x52, 0xca, 0xe8, 0x19, 0x38, 0x41, 0x1a, 0x65, 0x71, 0x82, 0x17, 0x94, 0x4c,
	0x29, 0xf3, 0x1a, 0xaa, 0x8e, 0x37, 0x2b, 0xd6, 0x27, 0x4a, 0xfe, 0x5a, 0x89, 0x7d, 0x3b, 0xa8,
	0xec, 0xd0, 0x53, 0xb8, 0x45, 0x22, 0xca, 0x04, 0xe6, 0x82, 0x44, 0xb4, 0x08, 0x09, 0x2f, 0xd2,
	0x8c, 0x71, 0xaf, 0xa9, 0x02, 0xbb, 0xa1, 0x14, 0x2e, 0xa4, 0x3c, 0x0f, 0xee, 0xb5, 0x94, 0xa2,
	0xcf, 0xe1, 0x20, 0xc9, 0x62, 0x3c, 0x23, 0x61, 0x94, 0x31, 0xca, 0xb1, 0x48, 0xb1, 0xd2, 0xf4,
	0x6c, 0x65, 0x86, 0x92, 0x2c, 0x7e, 0x99, 0xcb, 0xc6, 0xe9, 0xb1, 0x94, 0xa0, 0x1e, 0xb8, 0x41,
	0x3a, 0xa5, 0x98, 0x53, 0xc2, 0x82, 0x05, 0x5e, 0x12, 0xb1, 0xf0, 0x5a, 0x2a, 0xc3, 0x2d, 0x89,
	0x5f, 0x28, 0x78, 0x44, 0xc4, 0x02, 0x7d, 0x06, 0xd2, 0x1e, 0xeb, 0xbb, 0x72, 0xcc, 0x68, 0x40,
	0x13, 0xe1, 0xb5, 0x95, 0x67, 0x37, 0xc9, 0x62, 0x1d, 0x12, 0xf7, 0x15, 0x8e, 0x8e, 0xe0, 0x20,
	0xe3, 0x14, 0x5f, 0x66, 0x13, 0xca, 0x12, 0x2a, 0x28, 0xc7, 0x41, 0x14, 0x4a, 0x03, 0x4f, 0xe5,
	0x7c, 0x2f, 0xe3, 0xf4, 0x6d, 0x29, 0x3b, 0x51, 0x22, 0xd9, 0xbd, 0x21, 0xc7, 0xf4, 0x4a, 0x50,
	0x96, 0x90, 0xc8, 0xbb, 0xa5, 0x34, 0x21, 0xe4, 0x83, 0x1c, 0x41, 0x4f, 0xc1, 0x95, 0xb9, 0xd6,
	0x95, 0xc9, 0x3b, 0xf6, 0x76, 0xc7, 0xe8, 0x35, 0x8f, 0xda, 0x1f, 0xcd, 0x88, 0xdf, 0x12, 0xeb,
	0xb3, 0xf5, 0x04, 0x9c, 0xa4, 0xd2, 0xb2, 0xdc, 0xbb, 0xa3, 0x6a, 0xe2, 0xf4, 0xab, 0x8d, 0xec,
	0xaf, 0xeb, 0xa0, 0x67, 0x70, 0x47, 0x86, 0xbc, 0x24, 0x9c, 0xeb, 0x6c, 0x4e, 0x43, 0x4e, 0x26,
	0x11, 0xcd, 0xb3, 0x7a, 0xa8, 0x62, 0xbf, 0x99, 0x64, 0xf1, 0x48, 0x69, 0x8c, 0xd3, 0x53, 0x2d,
	0xd7, 0xa9, 0x7d, 0x08, 0xbb, 0x7c, 0x91, 0x32, 0x81, 0x55, 0xfb, 0xc7, 0x54, 0xb0, 0x30, 0xf0,
	0x1e, 0xa9, 0xdc, 0xb6, 0x95, 0x60, 0x4c, 0xaf, 0xc4, 0x99, 0x82, 0x6f, 0xbf, 0x05, 0xbb, 0xda,
	0x12, 0xe8, 0x31, 0xec, 0xe9, 0xf8, 0x32, 0xa6, 0xee, 0x82, 0x7f, 0x24, 0x51, 0x46, 0x55, 0x5f,
	0x37, 0x7c, 0xb4, 0x26, 0xfa, 0x41, 0x4a, 0xca, 0x21, 0xad, 0xb9, 0x5b, 0x5d, 0xaa, 0x07, 0x4a,
	0xb5, 0x24, 0x42, 0xd0, 0x1a, 0x0f, 0x2e, 0xc6, 0x17, 0xf8, 0xfc, 0xf8, 0x6c, 0x80, 0xcf, 0xde,
	0x9c, 0xbb, 0xff, 0x43, 0x07, 0xb0, 0x5b, 0xc1, 0xde, 0xbc, 0x3a, 0x7f, 0xef, 0x0f, 0x5c, 0x03,
	0xdd, 0x00, 0x54, 0x81, 0xfd, 0xc1, 0xe8, 0xdd, 0xf1, 0xc9, 0xc0, 0xad, 0x7d, 0xa4, 0x7e, 0x3c,
	0x1a, 0x0d, 0xce, 0x4f, 0xdd, 0xad, 0xa1, 0x69, 0xd5, 0xdd, 0xed, 0xa1, 0x69, 0xed, 0xb8, 0xd6,
	0xd0, 0xb4, 0x2c, 0xb7, 0x31, 0x34, 0x2d, 0x70, 0x9b, 0x43, 0xd3, 0x72, 0xdc, 0xd6, 0xd0, 0xb4,
	0x5c, 0xd7, 0x1b, 0x9a, 0xd6, 0x5d, 0xf7, 0xb0, 0xfb, 0x8b, 0x01, 0x8d, 0x53, 0xc2, 0x17, 0x93,
	0x94, 0xb0, 0x29, 0x3a, 0x02, 0x67, 0x5a, 0x6c, 0xb0, 0x20, 0x93, 0x9c, 0xe6, 0x9c, 0x7e, 0xa9,
	0x32, 0x26, 0x13, 0xdf, 0x9e, 0x56, 0x76, 0x25, 0x2d, 0xd4, 0x2a, 0xb4, 0xf0, 0x97, 0x92, 0x6e,
	0xfd, 0x83, 0x92, 0xde, 0x83, 0xe6, 0x94, 0xce, 0x48, 0x16, 0x09, 0x75, 0x74, 0x5d, 0x33, 0x64,
	0x0e, 0x8d, 0xc9, 0x24, 0x67, 0xb8, 0x11, 0xd8, 0x92, 0x9c, 0xc6, 0x34, 0x5e, 0x46, 0x44, 0x50,
	0xe4, 0xc2, 0x56, 0xc6, 0xa2, 0x9c, 0x95, 0xe4, 0x12, 0xf5, 0x61, 0x27, 0x5d, 0xea, 0x73, 0x6b,
	0xea, 0xdc, 0xfd, 0xbe, 0xb4, 0x78, 0xaf, 0xb1, 0xc2, 0xd0, 0x2f, 0x94, 0xba, 0xcf, 0x61, 0x6f,
	0x83, 0x5c, 0x3a, 0xbe, 0xa4, 0x05, 0x6d, 0xca, 0x25, 0xda, 0x87, 0xba, 0x2e, 0xb6, 0x8e, 0x55,
	0x6f, 0xba, 0xbf, 0xd6, 0xc1, 0x3e, 0xdd, 0x94, 0x91, 0x2a, 0x51, 0x1e, 0x82, 0xe2, 0x22, 0x3c,
	0x97, 0x1c, 0x83, 0x2b, 0x09, 0x73, 0x44, 0xc1, 0x3c, 0xaa, 0x27, 0x1e, 0x80, 0x33, 0xc9, 0xe6,
	0x38, 0x48, 0xe3, 0x65, 0x9a, 0xc8, 0xa1, 0xd4, 0x7c, 0x69, 0x4f, 0xb2, 0xf9, 0x49, 0x81, 0x6d,
	0x64, 0x06, 0xf3, 0x5f, 0x30, 0x43, 0xfd, 0x1a, 0x66, 0xb8, 0x0f, 0xf6, 0x84, 0x70, 0x8a, 0x8b,
	0xec, 0x6d, 0xeb, 0x5f, 0x82, 0xc4, 0xf2, 0xe4, 0xa0, 0xaf, 0x01, 0xa5, 0x4b, 0x9a, 0x60, 0x15,
	0x8c, 0xc8, 0x53, 0xe5, 0xed, 0xa8, 0x49, 0x77, 0xfa, 0xd5, 0xc2, 0xf8, 0xae, 0x54, 0x94, 0xdd,
	0x5e, 0x66, 0xf4, 0x29, 0xec, 0xce, 0xc2, 0x88, 0x62, 0x19, 0x61, 0x69, 0x6b, 0x6d, 0xb2, 0x6d,
	0x4b, 0xbd, 0xef, 0xb2, 0x79, 0x69, 0xfa, 0x1c, 0xf6, 0x88, 0x10, 0x24, 0x58, 0xac, 0x1b, 0x37,
	0x36, 0x19, 0xef, 0x6a, 0xcd, 0xaa, 0xf9, 0x7d, 0xb0, 0x0b, 0xb6, 0x96, 0x23, 0xef, 0x81, 0x8e,
	0x2c, 0xc7, 0xe4, 0xb4, 0xa3, 0x6f, 0x61, 0xbf, 0x50, 0xc9, 0x58, 0xb4, 0x3a, 0xa2, 0xb9, 0xe9,
	0x08, 0x94, 0xab, 0x7e, 0xcf, 0xa2, 0xf2, 0x8c, 0x97, 0xe0, 0x55, 0xab, 0xb2, 0xe6, 0xc4, 0xde,
	0xe4, 0xe4, 0x60, 0x55, 0xac, 0xaa, 0x9f, 0x8e, 0x9c, 0x03, 0x1e, 0xb0, 0x50, 0xa5, 0xdc, 0x73,
	0xf4, 0x55, 0x2b, 0x10, 0xfa, 0x06, 0x1c, 0xfd, 0x1f, 0x2a, 0x0a, 0xd5, 0x56, 0xee, 0x6f, 0xad,
	0x8d, 0xa9, 0x62, 0xba, 0xbc, 0x6c, 0xbe, 0x4d, 0x2a, 0xbb, 0xa1, 0x69, 0xb5, 0xdc, 0x76, 0xf7,
	0x77, 0x03, 0xbc, 0xeb, 0x0c, 0xfe, 0xfe, 0x57, 0x67, 0xfc, 0xb7, 0x5f, 0x5d, 0xed, 0xda, 0x5f,
	0xdd, 0x17, 0x70, 0x53, 0x9f, 0x16, 0x93, 0x30, 0x52, 0x06, 0xd3, 0x29, 0xa3, 0x92, 0xb8, 0x73,
	0x5e, 0xdd, 0x57, 0xe2, 0x33, 0x12, 0x46, 0xe3, 0xf4, 0xb8, 0x90, 0x75, 0xcf, 0xa0, 0x55, 0x06,
	0x70, 0xfd, 0x1b, 0xe5, 0x53, 0xf9, 0x08, 0x29, 0x48, 0x4d, 0x22, 0x9a, 0x16, 0x1a, 0x7e, 0xab,
	0x84, 0xe5, 0xe8, 0xf1, 0xee, 0xcf, 0x06, 0x38, 0x27, 0x55, 0xfe, 0x46, 0x8f, 0xa0, 0xb9, 0x9a,
	0xda, 0xe2, 0xd1, 0x07, 0xab, 0xc7, 0x82, 0x0f, 0xe5, 0xf4, 0x72, 0xf4, 0x10, 0xa0, 0x74, 0x58,
	0x30, 0x0f, 0xac, 0x4a, 0xe2, 0x57, 0xa4, 0xe8, 0x2b, 0x70, 0x57, 0x77, 0xca, 0xbd, 0x6b, 0x8e,
	0x6c, 0xf7, 0xd7, 0x43, 0xf2, 0x57, 0x97, 0xd7, 0xe7, 0x74, 0x7f, 0x32, 0x60, 0xff, 0x54, 0xb3,
	0xe2, 0xfa, 0x6d, 0xbf, 0x04, 0x54, 0x12, 0x68, 0x79, 0x6b, 0x95, 0x8a, 0xf5, 0x4b, 0xbb, 0x05,
	0xa7, 0x96, 0x4f, 0xbb, 0x63, 0x38, 0x28, 0x2c, 0xd7, 0xf9, 0xbf, 0x96, 0xf7, 0xed, 0x1a, 0xff,
	0xef, 0xe5, 0xba, 0x55, 0x70, 0xb2, 0xad, 0xde, 0xce, 0x4f, 0xfe, 0x0c, 0x00, 0x00, 0xff, 0xff,
	0x9e, 0x2c, 0x44, 0xbc, 0x5b, 0x0b, 0x00, 0x00,
}
