// Code generated by protoc-gen-go. DO NOT EDIT.
// source: testgrid/state/state.proto

package state

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Row_Result int32

const (
	Row_NO_RESULT        Row_Result = 0
	Row_PASS             Row_Result = 1
	Row_PASS_WITH_ERRORS Row_Result = 2
	Row_PASS_WITH_SKIPS  Row_Result = 3
	Row_RUNNING          Row_Result = 4
	Row_FAIL             Row_Result = 12
	Row_FLAKY            Row_Result = 13
)

var Row_Result_name = map[int32]string{
	0:  "NO_RESULT",
	1:  "PASS",
	2:  "PASS_WITH_ERRORS",
	3:  "PASS_WITH_SKIPS",
	4:  "RUNNING",
	12: "FAIL",
	13: "FLAKY",
}
var Row_Result_value = map[string]int32{
	"NO_RESULT":        0,
	"PASS":             1,
	"PASS_WITH_ERRORS": 2,
	"PASS_WITH_SKIPS":  3,
	"RUNNING":          4,
	"FAIL":             12,
	"FLAKY":            13,
}

func (x Row_Result) String() string {
	return proto.EnumName(Row_Result_name, int32(x))
}
func (Row_Result) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_state_cd7e9655cd78c9d6, []int{2, 0}
}

type Column struct {
	Build                string   `protobuf:"bytes,1,opt,name=build,proto3" json:"build,omitempty"`
	Started              float64  `protobuf:"fixed64,3,opt,name=started,proto3" json:"started,omitempty"`
	Extra                []string `protobuf:"bytes,4,rep,name=extra,proto3" json:"extra,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Column) Reset()         { *m = Column{} }
func (m *Column) String() string { return proto.CompactTextString(m) }
func (*Column) ProtoMessage()    {}
func (*Column) Descriptor() ([]byte, []int) {
	return fileDescriptor_state_cd7e9655cd78c9d6, []int{0}
}
func (m *Column) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Column.Unmarshal(m, b)
}
func (m *Column) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Column.Marshal(b, m, deterministic)
}
func (dst *Column) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Column.Merge(dst, src)
}
func (m *Column) XXX_Size() int {
	return xxx_messageInfo_Column.Size(m)
}
func (m *Column) XXX_DiscardUnknown() {
	xxx_messageInfo_Column.DiscardUnknown(m)
}

var xxx_messageInfo_Column proto.InternalMessageInfo

func (m *Column) GetBuild() string {
	if m != nil {
		return m.Build
	}
	return ""
}

func (m *Column) GetStarted() float64 {
	if m != nil {
		return m.Started
	}
	return 0
}

func (m *Column) GetExtra() []string {
	if m != nil {
		return m.Extra
	}
	return nil
}

type Metric struct {
	Name                 string    `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Indices              []int32   `protobuf:"varint,2,rep,packed,name=indices,proto3" json:"indices,omitempty"`
	Values               []float64 `protobuf:"fixed64,3,rep,packed,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Metric) Reset()         { *m = Metric{} }
func (m *Metric) String() string { return proto.CompactTextString(m) }
func (*Metric) ProtoMessage()    {}
func (*Metric) Descriptor() ([]byte, []int) {
	return fileDescriptor_state_cd7e9655cd78c9d6, []int{1}
}
func (m *Metric) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Metric.Unmarshal(m, b)
}
func (m *Metric) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Metric.Marshal(b, m, deterministic)
}
func (dst *Metric) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Metric.Merge(dst, src)
}
func (m *Metric) XXX_Size() int {
	return xxx_messageInfo_Metric.Size(m)
}
func (m *Metric) XXX_DiscardUnknown() {
	xxx_messageInfo_Metric.DiscardUnknown(m)
}

var xxx_messageInfo_Metric proto.InternalMessageInfo

func (m *Metric) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Metric) GetIndices() []int32 {
	if m != nil {
		return m.Indices
	}
	return nil
}

func (m *Metric) GetValues() []float64 {
	if m != nil {
		return m.Values
	}
	return nil
}

type Row struct {
	Name                 string    `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id                   string    `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Results              []int32   `protobuf:"varint,3,rep,packed,name=results,proto3" json:"results,omitempty"`
	CellIds              []string  `protobuf:"bytes,4,rep,name=cell_ids,json=cellIds,proto3" json:"cell_ids,omitempty"`
	Messages             []string  `protobuf:"bytes,5,rep,name=messages,proto3" json:"messages,omitempty"`
	Metrics              []*Metric `protobuf:"bytes,8,rep,name=metrics,proto3" json:"metrics,omitempty"`
	Icons                []string  `protobuf:"bytes,9,rep,name=icons,proto3" json:"icons,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Row) Reset()         { *m = Row{} }
func (m *Row) String() string { return proto.CompactTextString(m) }
func (*Row) ProtoMessage()    {}
func (*Row) Descriptor() ([]byte, []int) {
	return fileDescriptor_state_cd7e9655cd78c9d6, []int{2}
}
func (m *Row) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Row.Unmarshal(m, b)
}
func (m *Row) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Row.Marshal(b, m, deterministic)
}
func (dst *Row) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Row.Merge(dst, src)
}
func (m *Row) XXX_Size() int {
	return xxx_messageInfo_Row.Size(m)
}
func (m *Row) XXX_DiscardUnknown() {
	xxx_messageInfo_Row.DiscardUnknown(m)
}

var xxx_messageInfo_Row proto.InternalMessageInfo

func (m *Row) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Row) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Row) GetResults() []int32 {
	if m != nil {
		return m.Results
	}
	return nil
}

func (m *Row) GetCellIds() []string {
	if m != nil {
		return m.CellIds
	}
	return nil
}

func (m *Row) GetMessages() []string {
	if m != nil {
		return m.Messages
	}
	return nil
}

func (m *Row) GetMetrics() []*Metric {
	if m != nil {
		return m.Metrics
	}
	return nil
}

func (m *Row) GetIcons() []string {
	if m != nil {
		return m.Icons
	}
	return nil
}

type Grid struct {
	Columns              []*Column `protobuf:"bytes,1,rep,name=columns,proto3" json:"columns,omitempty"`
	Rows                 []*Row    `protobuf:"bytes,2,rep,name=rows,proto3" json:"rows,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Grid) Reset()         { *m = Grid{} }
func (m *Grid) String() string { return proto.CompactTextString(m) }
func (*Grid) ProtoMessage()    {}
func (*Grid) Descriptor() ([]byte, []int) {
	return fileDescriptor_state_cd7e9655cd78c9d6, []int{3}
}
func (m *Grid) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Grid.Unmarshal(m, b)
}
func (m *Grid) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Grid.Marshal(b, m, deterministic)
}
func (dst *Grid) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Grid.Merge(dst, src)
}
func (m *Grid) XXX_Size() int {
	return xxx_messageInfo_Grid.Size(m)
}
func (m *Grid) XXX_DiscardUnknown() {
	xxx_messageInfo_Grid.DiscardUnknown(m)
}

var xxx_messageInfo_Grid proto.InternalMessageInfo

func (m *Grid) GetColumns() []*Column {
	if m != nil {
		return m.Columns
	}
	return nil
}

func (m *Grid) GetRows() []*Row {
	if m != nil {
		return m.Rows
	}
	return nil
}

func init() {
	proto.RegisterType((*Column)(nil), "Column")
	proto.RegisterType((*Metric)(nil), "Metric")
	proto.RegisterType((*Row)(nil), "Row")
	proto.RegisterType((*Grid)(nil), "Grid")
	proto.RegisterEnum("Row_Result", Row_Result_name, Row_Result_value)
}

func init() { proto.RegisterFile("testgrid/state/state.proto", fileDescriptor_state_cd7e9655cd78c9d6) }

var fileDescriptor_state_cd7e9655cd78c9d6 = []byte{
	// 407 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0xc1, 0x6e, 0x9b, 0x40,
	0x10, 0x86, 0x0b, 0xbb, 0xc0, 0x7a, 0x68, 0xda, 0xd5, 0x36, 0xaa, 0xb6, 0x39, 0x51, 0x4e, 0x9c,
	0x5c, 0x29, 0x7d, 0x02, 0xab, 0x4a, 0x52, 0x1c, 0x97, 0x44, 0x83, 0xa3, 0xaa, 0x27, 0x8b, 0xc0,
	0xca, 0x5a, 0x09, 0x9b, 0x8a, 0x5d, 0xd7, 0x7d, 0xb1, 0xbe, 0x5f, 0xc5, 0x02, 0xed, 0x25, 0x17,
	0x34, 0xdf, 0xcf, 0xe8, 0x67, 0xfe, 0x19, 0xe0, 0xca, 0x2a, 0x63, 0xf7, 0xbd, 0x6e, 0x3e, 0x19,
	0x5b, 0x59, 0x35, 0x3e, 0x97, 0x3f, 0xfb, 0xce, 0x76, 0xe9, 0x16, 0xc2, 0x2f, 0x5d, 0x7b, 0x3a,
	0x1c, 0xc5, 0x25, 0x04, 0xcf, 0x27, 0xdd, 0x36, 0xd2, 0x4b, 0xbc, 0x6c, 0x81, 0x23, 0x08, 0x09,
	0x91, 0xb1, 0x55, 0x6f, 0x55, 0x23, 0x49, 0xe2, 0x65, 0x1e, 0xce, 0x38, 0xf4, 0xab, 0xdf, 0xb6,
	0xaf, 0x24, 0x4d, 0xc8, 0xd0, 0xef, 0x60, 0x4d, 0x99, 0xcf, 0x49, 0x5a, 0x40, 0xf8, 0x4d, 0xd9,
	0x5e, 0xd7, 0x42, 0x00, 0x3d, 0x56, 0x07, 0x35, 0x99, 0xba, 0x7a, 0xf0, 0xd4, 0xc7, 0x46, 0xd7,
	0xca, 0x48, 0x3f, 0x21, 0x59, 0x80, 0x33, 0x8a, 0xf7, 0x10, 0xfe, 0xaa, 0xda, 0x93, 0x32, 0x92,
	0x24, 0x24, 0xf3, 0x70, 0xa2, 0xf4, 0x8f, 0x0f, 0x04, 0xbb, 0xf3, 0x8b, 0x6e, 0x6f, 0xc0, 0xd7,
	0x8d, 0xf4, 0x9d, 0xe2, 0x6b, 0x37, 0x71, 0xaf, 0xcc, 0xa9, 0xb5, 0xa3, 0x49, 0x80, 0x33, 0x8a,
	0x0f, 0xc0, 0x6a, 0xd5, 0xb6, 0x3b, 0xdd, 0x98, 0x69, 0xe8, 0x68, 0xe0, 0xbc, 0x31, 0xe2, 0x0a,
	0xd8, 0x41, 0x19, 0x53, 0xed, 0x95, 0x91, 0x81, 0x7b, 0xf5, 0x8f, 0xc5, 0x47, 0x88, 0x0e, 0x2e,
	0x8c, 0x91, 0x2c, 0x21, 0x59, 0x7c, 0x1d, 0x2d, 0xc7, 0x70, 0x38, 0xeb, 0xc3, 0x2e, 0x74, 0xdd,
	0x1d, 0x8d, 0x5c, 0x8c, 0xbb, 0x70, 0x90, 0x5a, 0x08, 0xd1, 0x7d, 0x5a, 0x5c, 0xc0, 0xa2, 0x78,
	0xd8, 0xe1, 0x4d, 0xf9, 0xb4, 0xd9, 0xf2, 0x57, 0x82, 0x01, 0x7d, 0x5c, 0x95, 0x25, 0xf7, 0xc4,
	0x25, 0xf0, 0xa1, 0xda, 0x7d, 0xcf, 0xb7, 0x5f, 0x77, 0x37, 0x88, 0x0f, 0x58, 0x72, 0x5f, 0xbc,
	0x83, 0xb7, 0xff, 0xd5, 0xf2, 0x3e, 0x7f, 0x2c, 0x39, 0x11, 0x31, 0x44, 0xf8, 0x54, 0x14, 0x79,
	0x71, 0xc7, 0xe9, 0xe0, 0x70, 0xbb, 0xca, 0x37, 0xfc, 0xb5, 0x58, 0x40, 0x70, 0xbb, 0x59, 0xdd,
	0xff, 0xe0, 0x17, 0x29, 0x65, 0x01, 0x8f, 0xd7, 0x94, 0x85, 0x9c, 0xad, 0x29, 0x03, 0x1e, 0xa7,
	0x39, 0xd0, 0xbb, 0x5e, 0x37, 0x43, 0x84, 0xda, 0x5d, 0xd9, 0x48, 0x6f, 0x8a, 0x30, 0x5e, 0x1d,
	0x67, 0x5d, 0x48, 0xa0, 0x7d, 0x77, 0x1e, 0x2f, 0x12, 0x5f, 0xd3, 0x25, 0x76, 0x67, 0x74, 0xca,
	0x9a, 0x32, 0xc2, 0xe1, 0x39, 0x74, 0xff, 0xcb, 0xe7, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x34,
	0xf1, 0x21, 0x88, 0x4d, 0x02, 0x00, 0x00,
}
